SELECT DISTINCT C1.CART_ID
FROM CART_PRODUCTS C1
INNER JOIN CART_PRODUCTS C2
ON C1.CART_ID = C2.CART_ID
WHERE (C1.NAME = 'MILK' AND C2.NAME = 'YOGURT') OR (C2.NAME = 'MILK' AND C1.NAME = 'YOGURT')
ORDER BY 1;