WITH RECURSIVE RC AS (
    SELECT ID, PARENT_ID, 2 AS GE
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    UNION ALL
    SELECT D.ID, D.PARENT_ID, R.GE+1
    FROM ECOLI_DATA D
    INNER JOIN RC R
    ON D.PARENT_ID = R.ID
)

SELECT ID
FROM RC
GROUP BY ID
HAVING MAX(GE) = 3
ORDER BY ID;