SELECT CC.CAR_ID, CC.CAR_TYPE, 
       ROUND(CC.DAILY_FEE * 30 * (100 - CP.DISCOUNT_RATE)/100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR CC
        LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
        ON CC.CAR_TYPE = CP.CAR_TYPE AND CP.DURATION_TYPE = '30일 이상'
    WHERE CC.CAR_ID NOT IN (
        SELECT CH.CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
            WHERE START_DATE <= '2022-12-01' AND END_DATE >= '2022-11-01'
        )
      AND CC.CAR_TYPE IN ('세단', 'SUV')
     HAVING FEE >= 500000 AND FEE < 2000000
     ORDER BY FEE DESC, CC.CAR_TYPE, CC.CAR_ID DESC