SELECT DISTINCT P.FOOD_TYPE, P.REST_ID, P.REST_NAME, P.FAVORITES FROM REST_INFO P 
INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) F
ON P.FOOD_TYPE = F.FOOD_TYPE AND P.FAVORITES = F.FAVORITES
ORDER BY P.FOOD_TYPE DESC;