SELECT E1.ID, CASE 
    WHEN E2.SIZE_PERCENT <= 0.25 THEN 'CRITICAL'
    WHEN E2.SIZE_PERCENT <= 0.5 THEN 'HIGH'
    WHEN E2.SIZE_PERCENT <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW' END
COLONY_NAME
FROM ECOLI_DATA E1
INNER JOIN(
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS SIZE_PERCENT
    FROM ECOLI_DATA
) AS E2 ON E1.ID = E2.ID
ORDER BY 1;