SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
CONCAT(SUBSTR(U.TLNO, 1, 3), '-', SUBSTR(U.TLNO, 4, 4), '-', SUBSTR(U.TLNO, 8)) AS '전화번호'
FROM USED_GOODS_USER U
INNER JOIN (
    SELECT WRITER_ID, COUNT(BOARD_ID) AS TOTAL
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING TOTAL>=3
) AS B
ON U.USER_ID = B.WRITER_ID
ORDER BY 1 DESC;