SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS 전체주소,
CONCAT(SUBSTR(U.TLNO, 1, 3), '-', SUBSTR(U.TLNO, 4, 4), '-', SUBSTR(U.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER U INNER JOIN (
    SELECT WRITER_ID, COUNT(BOARD_ID) AS 합
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
) AS B ON U.USER_ID = B.WRITER_ID
WHERE B.합 >= 3
ORDER BY 1 DESC;