WITH RECURSIVE GENERATION AS
(
    SELECT ID
         , PARENT_ID
         , 1 AS GEN
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.ID
         , A.PARENT_ID
         , GEN + 1 AS GEN
        FROM ECOLI_DATA A
            INNER JOIN GENERATION B
            ON A.PARENT_ID = B.ID
)
SELECT COUNT(*) AS COUNT,  GEN AS GENERATION
    FROM GENERATION
    WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
    GROUP BY GEN