SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES 
FROM FOOD_PRODUCT P
INNER JOIN FOOD_ORDER O
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY P.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;