SELECT U.USER_ID, U.NICKNAME, B.PRICE AS TOTAL_SALES FROM USED_GOODS_USER U INNER JOIN(
    SELECT WRITER_ID, SUM(PRICE) AS PRICE FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) AS B ON U.USER_ID = B.WRITER_ID
WHERE PRICE >= 700000
ORDER BY 3;