SELECT M.MEMBER_NAME, R1.REVIEW_TEXT, DATE_FORMAT(R1.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M
INNER JOIN REST_REVIEW R1
ON M.MEMBER_ID = R1.MEMBER_ID
INNER JOIN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
) AS R2
ON M.MEMBER_ID = R2.MEMBER_ID
ORDER BY 3, 2;