SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C INNER JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <='2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) AS F ON C.CAR_ID = F.CAR_ID
WHERE C.START_DATE >= '2022-08-01' AND C.START_DATE <='2022-10-31'
GROUP BY 1, 2
ORDER BY 1, 2 DESC;