SELECT YEAR(D1.DIFFERENTIATION_DATE) AS YEAR, D2.MAX_VALUE-D1.SIZE_OF_COLONY AS YEAR_DEV, D1.ID
FROM ECOLI_DATA D1
LEFT JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_VALUE
    FROM ECOLI_DATA
    GROUP BY 1
) AS D2
ON YEAR(D1.DIFFERENTIATION_DATE) = D2.YEAR
ORDER BY 1, 2;