SELECT C.CAR_ID FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN (
    SELECT DISTINCT F.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY F
    WHERE F.START_DATE >= '2022-10-01'
) AS F ON F.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단'
ORDER BY 1 DESC;