SELECT F1.ID, FN.FISH_NAME , F1.LENGTH
    FROM FISH_INFO F1
        INNER JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
                        FROM FISH_INFO
                        WHERE LENGTH IS NOT NULL
                        GROUP BY FISH_TYPE) F2
        ON F1.FISH_TYPE = F2.FISH_TYPE AND F1.LENGTH = F2.LENGTH
            INNER JOIN FISH_NAME_INFO FN
            ON F1.FISH_TYPE = FN.FISH_TYPE
    ORDER BY F1.ID;