SELECT HG.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
    FROM HR_EMPLOYEES HE
        INNER JOIN ( SELECT EMP_NO, YEAR, SUM(SCORE) AS SCORE
                        FROM HR_GRADE 
                        GROUP BY EMP_NO, YEAR) AS HG
        ON HE.EMP_NO = HG.EMP_NO
    WHERE HG.YEAR = 2022
    ORDER BY HG.SCORE DESC
    LIMIT 1;