SELECT COUNT(*) AS FISH_COUNT, MAX(F.LENGTH) AS MAX_LENGTH, F.FISH_TYPE
FROM FISH_INFO F
INNER JOIN (
    SELECT FISH_TYPE, AVG(CASE WHEN LENGTH IS NULL THEN 10
                         ELSE LENGTH END) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH >= 33
) AS I 
ON F.FISH_TYPE = I.FISH_TYPE
GROUP BY FISH_TYPE
ORDER BY 3 ASC